---
- name: web
  hosts: localhost
  become: yes
  
  tasks: 
    - name: Set placement preferences
      docker_swarm_service:
        name: myweb
        image: nginx
        placement:
          constraints:
            - node.role == worker

