---
- name: web
  hosts: localhost
  become: yes
  
  tasks:
    - name: Install python3-apt
      apt:
        name: python3-apt
        state: present
    
    - name: nginx
      apt:
        name: nginx
        state: present
    - name: index.html
      get_url:
        url: https://www.jobkorea.com
        dest: /var/www/html
    - name: service 
      service:
        name: nginx
        state: started
        enabled: true
    - name: ufw
      service:
        name: ufw
        state: stopped
        enabled: false
