
---
- name: web
  hosts: all
  become: yes
  
  tasks:
    - name: nginx
      shell: docker service create --name test1 --replicas 3 --constraint node.role==worker --with-registry-auth -p 8001:80 nginx
